name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: '3.11'
        environment-file: environment.yml
        activate-environment: standard-setup
        auto-activate-base: false

    - name: Display Python version and environment
      run: |
        which python
        python --version
        echo "Active environment:"
        conda info --envs

    - name: Lint with flake8
      run: |
        echo "Running flake8 for linting:"
        flake8 .

    - name: Test with pytest
      run: |
        echo "Running tests with pytest:"
        pytest
