name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: standard-setup

    - name: Add conda to system path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        echo "Current Python version:"
        python --version
        echo "Installing Python 3.11 explicitly:"
        conda install -y python=3.11
        echo "Rechecking Python version:"
        python --version
        echo "Updating environment:"
        conda env update --file environment.yml --name standard-setup
        echo "Activating environment:"
        source activate standard-setup

    - name: Lint with flake8
      run: |
        echo "Running flake8 for linting:"
        conda install -y flake8
        flake8 .

    - name: Test with pytest
      run: |
        echo "Running tests with pytest:"
        conda install -y pytest
        pytest