name: standard-setup
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - jupyter
  - notebook
  - ipython
  - ipykernel
  - statsmodels
  - pip
  - pip:
    - tensorflow
    - keras
    - plotly
    - lxml
    - beautifulsoup4
    - requests
    - opencage
    - streamlit