name: standard-setup
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.22
  - pandas=1.4
  - matplotlib=3.5
  - seaborn=0.11
  - scikit-learn=1.0
  - scipy=1.7
  - jupyter
  - notebook
  - ipython
  - ipykernel
  - statsmodels=0.13
  - pip
  - pip:
    - tensorflow==2.9 
    - keras==2.9        
    - plotly==5.5
    - "lxml"==4.8
    - beautifulsoup4==4.11
    - requests==2.28
    - folium==0.12.1
    - opencage==2.0
    - streamlit==1.10
