name: standard-setup
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - jupyter
  - notebook
  - ipython
  - ipykernel
  - statsmodels
  - folium
  - geopandas
  - pip:
    - streamlit
    - tensorflow
    - keras
    - plotly
    - "lxml"
    - beautifulsoup4
    - requests
    - opencage
    - geopy
    - pydeck